import Head from 'next/head'
import SpeedReader from '../components/reader/SpeedReader'

export default function Home() {
  return (
    <>
      <Head>
        <title>Speed Reader</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SpeedReader />
    </>
  )
}
